### ISSUE TITLE
Enforce EnergyPlus's Limit of 10 material layers for constructions

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#10]
Right now, we do a check to make sure that there is [at least one material in each EnergyPlus construction](https://github.com/ladybug-tools-in2/energy-model-schema/blob/master/app/models/energy/construction.py#L797-L804). However, EnergyPlus also has an upper limit on the number of materials in a construction as you can see [here](https://bigladdersoftware.com/epx/docs/8-9/input-output-reference/group-surface-construction-elements.html#construction-000).  Specifically, this is:
```
Up to ten layers (eight for windows)
```
So we should have a built-in check to make sure that there are not more than 10 materials. In an ideal world, we also check to see if there are any WindowMaterials in the construction and then set the upper limit to 8 but we can do just 10 for now.

**Comment by tanushree04** [comment]
@chriswmackey, you are looking at a different version of the schema. 
The `EnergyConstructionTransparent` class has been updated in the current version to have no more than 8 materials, and the `EnergyConstructionOpaque` no more than 10 materials as mandated by the `@validator` decorator. 

Please find the current version of the schema here: https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py
