### ISSUE TITLE
Consider Changing EnergyConstructionTransparent to EnergyConstructionWindow

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#14]
@tanushree04 ,

Thinking over your [recent division of EnergyConstruction](https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py#L767-L847) into `EnergyConstructionOpaque` and `EnergyConstructionTransparent`, I am in general agreement that it makes sense to separate the construction objects that can be applied to windows from those that get applied to opaque surfaces.  It greatly simplifies the checking of the materials and makes it easy to check that a given construction is valid for a given surface in the model.  It's also more explicit from the perspective of the user, which is an improvement.

The one thing that I keep getting hung up on is the choice of the word "transparent" to describe all of the materials that can be applied to windows, including shades, gas gaps, light diffusing materials, etc.  I know that "transparent" is the logical opposite of "opaque" but it doesn't seem like the best term for what this type of construction includes.  So I am currently in favor of changing it to `EnergyConstructionWindow`, which is a bit accurate for describing all the things that can be included under this type of construction and takes its name from the `WindowMaterial` naming convention used in EnergyPlus.

If anyone has any other suggestions or reasons why they think `Transparent` is better, please voice them here. Otherwise, I think it is best to go through with the change to `EnergyConstructionWindow`

**Comment by macumber** [comment]
Also remember that sub surfaces can be doors (which are opaque), tubular daylighting devices, and skylights.  Here is the list in the OpenStudio IDD:

 ```
 A3, \field Sub Surface Type
       \type choice
       \required-field
       \key FixedWindow
       \key OperableWindow
       \key Door
       \key GlassDoor
       \key OverheadDoor
       \key Skylight
       \key TubularDaylightDome
       \key TubularDaylightDiffuser
```

**Comment by chriswmackey** [comment]
Thanks @macumber .  As you can see from the way the `ConstructionSet` object is being developed, the doors are being separated out into their own object that accepts opaque constructions.  Glass doors will be grouped with the other window types. We don't plan on supporting the two tubular types for now.
