### ISSUE TITLE
Follow PEP8 for the Custom Gas Type coefficients

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#16]
We intend to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) throughout the schema and the names for the gas coefficients are currently in violation of this.

So, for all of the coefficients in the custom gas [like this oone](https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py#L160), the following change should be made:

`conductivity_coeff_A` --> `conductivity_coeff_a`

**Comment by tanushree04** [comment]
Should I make [this](https://github.com/ladybug-tools-in2/energy-model-schema/blob/cb7ba504748fcb611afc024cf18e0f7415947bae/app/models/energy/construction.py#L256) `shgc`

**Comment by mostaphaRoudsari** [comment]
Hi @tanushree04, You can keep it as is. Acronyms are exceptions to the rule. See here:

https://github.com/ladybug-tools/contributing/wiki/python-style-guide#naming-convention-for-classes-representing-file-types

**Comment by chriswmackey** [comment]
@tanushree04 ,

Acronyms can be exceptions as @mostaphaRoudsari says but I feel that this case really should be lowercase for consistency with the other neighboring inputs.  I realize at this point its more of a gut feeling about style but I think that people will logically expect the name of the property to be `shgc` if the name of the neighboring property is `u_factor`.

The one place where I think you have total free licence to follow @mostaphaRoudsari 's rule and capitalize acronyms is in class names. You can see that [we do this in ladybug-core](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L24) for classes like `EPW`.
