### ISSUE TITLE
Remove random "greater than" checks in Custom Gas coefficients

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#17]
For some reason, some of the gas coefficients [like this one](https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py#L180) enforce "greater than 0" rules while others do not.  As I understand it, all of these coefficients can be positive or negative so I think we should remove these restrictions.

**Comment by tanushree04** [comment]
I added `viscosity_coeff_a` and `specific_heat_coeff_a` to be `>0` as per EnergyPlus.

**Comment by chriswmackey** [comment]
Ah. I just realized that this was listed in the documentation with the IDFEditor. Ok, it is good to enforce positive values for those two properties.  However, I see that you enforced for [B](https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py#L206) and [C](https://github.com/ladybug-tools-in2/energy-model-schema/blob/construction/app/models/energy/construction.py#L213) coefficients and these don't have the same restriction.
