### ISSUE TITLE
Separate out `times` and `values` in ScheduleDay into two lists

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#34]
In the current schema, the ScheduleDay value and the time it corresponds to are wrapped into one [DayValue](https://github.com/ladybug-tools-in2/energy-model-schema/blob/develop/app/models/energy/scheduleruleset.py#L36-L41) object.  However, this object only holds two properties and really has no meaning when it exists outside of a ScheduleDay.  So, instead, we would prefer to get rid of this object and just have two lists on the ScheduleDay (one with the values and one with the corresponding times). We would need a validator to make sure the list lengths match and we would also need validators to loop over each list and make sure the items are of the correct type.  However, this seems cleaner to me than the current situation and it could also make it easier to add a validator to check that all of the times for a schedule are sequential (something that we could live without but would be nice to have).

**Comment by tanushree04** [comment]
@chriswmackey I didnt understand what you meant by validators that loop in each list to make sure the items are the correct type.

**Comment by chriswmackey** [comment]
@tanushree04 ,

You were right to be confused by that.  I forgot that you can just specify that a property is an array of a list of Time objects. 

However, given the change noted here in combination with [this issue](https://github.com/ladybug-tools-in2/energy-model-schema/issues/32), we will need to check that all of the input times are arrays with two integers in them, which I think may require a validator.

**Comment by chriswmackey** [comment]
Done!
