### ISSUE TITLE
Refactor the repository

### ISSUE THREAD

**Issue by mostaphaRoudsari** [chriswmackey/energy-model-schema#55]
It looks like that this repository can be fully re-structured to only include the energy model schema which can then be imported to Pollination model service and other tools.

None of the rest of the end points are really required or related to this repository.

@chriswmackey, @tanushree04 what are your thoughts on this?

I suggest to do it at some point once you are in a stable state with no open PRs.

**Comment by chriswmackey** [comment]
I agree this needs to be refactored.  We also have several branches, which we aren't really using and should be deleted.

Let's to this after we merge in the PR for SimulationParameters.

**Comment by chriswmackey** [comment]
This has essentially been completed except that I know you are still going to clean it up a bit further, @mostaphaRoudsari . Do you want to leave it open until you make your changes?

**Comment by mostaphaRoudsari** [comment]
We can close this. I will open a new issue for the rest of the tasks.
