### ISSUE TITLE
Split the EnergyWindowMaterialAirGap into two separate objects

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#6]
Right now, the vast majority of the inputs on the `EnergyWindowMaterialAirGap` are only for the case of a custom gas in the gap.  Therefore, I think that we should have two separate classes for gasses within the schema:

`EnergyWindowMaterialGas` - This class should only have three required inputs: the `name`, the `gas_type` and the `thickness`. None of the other inputs should be there since they are not required when the gas is Air, Argon, Krypton or Xenon.  The `GasType` enumeration should therefore be updated to have the `Custom` gas removed.

`EnergyWindowMaterialGasCustom` - This class is only for custom gasses and has required inputs for all of the coefficients (including those for conductivity, viscosity, and specific heat).  It will lack a `gas_type` input since the coefficients give a complete description of the gas properties.

**Comment by chriswmackey** [comment]
To give an example of what we mean, we would point you towards how different skies are implemented in the honeybee radiance schema:
https://pollination.cloud/api/#operation/create_simulation

If you go to PointInTimeGridBasedIn and go under Skies, you will see that there are two options:
![image](https://user-images.githubusercontent.com/5567574/59453982-22a56980-8ddf-11e9-8e61-8676f9170948.png)

Each sky has its own schema ever though they both have some of the same properties.  Generally, speaking, this is the convention that we want to follow (splitting one schema in two) when there are differences of required inputs within a single schema.

**Comment by tanushree04** [comment]
Should I add default values for the `EnergyWindowMaterualGasCustom` [properties](https://github.com/ladybug-tools-in2/energy-model-schema/blob/cb7ba504748fcb611afc024cf18e0f7415947bae/app/models/energy/construction.py#L161) or list them as `required`properties?

**Comment by chriswmackey** [comment]
I think we should just make all of the `A` coefficients required but set the `B` and `C` coefficients to 0 by default.    You can see from [the formula in the E+ reference](https://bigladdersoftware.com/epx/docs/8-9/input-output-reference/group-surface-construction-elements.html#properties-for-custom-gas-types) that, when the B and C coefficients are 0, people can just plug in the actual values for conductivity, viscosity, and specific heat of the gas in the `A` fields.
