### ISSUE TITLE
Add A Class for GasMixture to materials schema

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#7]
The vast majority of inputs that people want to use for the gaps between panes of glass are either single gasses (like Air or Argon) or a gas mixture.  It would therefore be helpful to have a material for `GasMixutre` as part of the schema.

This would parallel the [GasMixture object in EnergyPlus](https://bigladdersoftware.com/epx/docs/8-9/input-output-reference/group-surface-construction-elements.html#windowmaterialgasmixture) but the input would be a lists of gasses and a corresponding list with fractions of gasses (instead of a separate input for each gas).  We would enforce that the gas fractions sum to 1 and that there is an equal list length of gases and fractions.

**Comment by macumber** [comment]
An alternative to two arrays of the same length (one for gas and one for fraction), is one array of objects with a gas and a faction property.  You'd still want the check that fractions sum to 1.

**Comment by tanushree04** [comment]
Should I add the check for the sum to be equal to 1 in the schema?
