### ISSUE TITLE
Enforce EnergyPlus's 100 character limit for names of materials, schedules, etc.

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/energy-model-schema#8]
EnergyPlus truncates any names of object that are longer than 100 characters, meaning that it can quickly become impossible to match outputs with inputs if we don't enforce this 100 character limit across the schema.

So, in any of the cases where we are doing a regex [like this](https://github.com/ladybug-tools-in2/energy-model-schema/blob/master/app/models/energy/construction.py#L244), we should also be doing a check to be sure that the name is not longer than 100 characters.  Come to think of it, we should also be checking to make sure that we don't end up with any 0-character names as well. So we generally want to make sure that:

`0 < len(name) <= 100`

**Comment by macumber** [comment]
Might want to restrict other characters like `! -` etc, regex like `[A-Za-z0-9_-\s]`

Would also remove unicode characters

Can also have a `display_name` field

**Comment by macumber** [comment]
Can't be empty either.  Do you ever check that names are unique?

**Comment by macumber** [comment]
OpenStudio ModelObjects now have AdditionalProperties object that can be used to store original name, id, or any other key/value pair.

**Comment by chriswmackey** [comment]
@macumber ,

Can you clarify what objects in the SDK have the `DisplayName`?  Does every object have it?
As I said in the call, I think we want to use it to keep track of the original name that people assign to Honeybee Faces but we might use it for other objects as well if it is available.

**Comment by macumber** [comment]
No objects have a display name separate from name, it would be an additional property
